const types = {
  // Example mutations
  INCREMENT_COUNT: "INCREMENT_COUNT",
  INCREMENT_COUNT_BY: "INCREMENT_COUNT_BY",
  SET_PLAYGROUND_STATE: "SET_PLAYGROUND_STATE",

  // Login mutations
  LOG_IN_USER: "LOG_IN_USER",
  LOG_OUT_USER: "LOG_OUT_USER",

  // User mutations
  SET_USER_PROFILE: "SET_USER_PROFILE",
  CLEAR_USER_PROFILE: "CLEAR_USER_PROFILE",

  // Wishlist mutations
  SET_WISHLIST_ITEMS: "SET_WISHLIST_ITEMS",
  ADD_WISHLIST_ITEM: "ADD_WISHLIST_ITEM"
};

export default types;
